___
## Módulo 2:  Introducción a las librerías Numpy, Pandas y Matplotlib.
___

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### 2.1. Introducción a NumPy I.

**2.1.1.**  Crea un vector con valores de 10 a 49 en pasos de 0.5.

In [ ]:
vect = np.arange(10, 49, 0.5)
vect

**2.1.2.** Muestra su dimensión y su tipo.

In [ ]:
vect.shape

In [ ]:
vect.dtype

**2.1.3.** Crea un array con los números que elijas de dimensiones 2x3.

In [ ]:
lista_para_arr = [
    [1,2,3],
    [1,4,2],
]

In [ ]:
np.array(lista_para_arr)

**2.1.4.** Indexing y slicing:

- Crea un array unidimensional de 10 elemento aleatorios.
- Crea un array bidimensional de 10x10 elementos aletorios.
- Accede al primer elemento y al penúltimo número de cada array. 
- Para el array unidimensional: muestra todos los elementos en posiciones pares desde la posición 6. 
- Para el array bidimensional: muestra una submatriz con las dos primeras filas y las tres primeras columnas.
- Divide el array bidimensional en dos: uno con las 2 primera filas y otro con las siguientes

In [ ]:
uni = np.random.rand(10)
bi_dim = np.random.rand(10, 10)

In [ ]:
uni.shape

In [ ]:
bi_dim.shape

In [ ]:
print(uni[0])
print(uni[-2])

In [ ]:
print(bi_dim[0, 0])
print(bi_dim[-2,-2])

In [ ]:
uni[6::2]

In [ ]:
bi_dim[:2,:3]

In [ ]:
vector = np.random.rand(1, 10)

print(vector.shape)
print(vector.T.shape)

In [ ]:
bi_dim_a = bi_dim[:2,:]
bi_dim_b = bi_dim[2:,:]

In [ ]:
bi_dim_a

In [ ]:
bi_dim_b

**2.1.5.** Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la diagonal principal valgan 5 y el resto valgan n.

In [ ]:
def fun(n):
    return np.eye(n)*5

In [ ]:
fun(3)

**2.1.6.** Crea un vector de 30 elementos aleatorios y calcula su media.

In [3]:
vector = np.random.random(30)

In [4]:
np.mean(vector)

0.4762089124894276

In [5]:
vector.mean()

0.4762089124894276

**2.1.7.** Crea una matriz de 8x10 aleatoria y substrae la media por columnas.

In [6]:
matriz = np.random.randint(1, 10, (8,10))
matriz

array([[9, 3, 5, 3, 9, 7, 5, 9, 5, 7],
       [1, 2, 6, 6, 9, 1, 4, 8, 1, 1],
       [1, 9, 8, 4, 8, 9, 5, 3, 9, 8],
       [2, 1, 8, 3, 4, 5, 8, 1, 3, 8],
       [1, 3, 2, 8, 8, 9, 9, 4, 8, 5],
       [1, 2, 8, 9, 8, 9, 4, 6, 8, 6],
       [8, 1, 1, 1, 5, 4, 1, 9, 2, 6],
       [1, 2, 2, 7, 1, 8, 6, 5, 8, 5]])

In [7]:
matriz.shape

(8, 10)

In [13]:
matriz.mean(axis=0)

array([3.   , 2.875, 5.   , 5.125, 6.5  , 6.5  , 5.25 , 5.625, 5.5  ,
       5.75 ])

**2.1.8.** Crea una función que reciba dos enteros n y m, 

- Genere dos matrices aleatorias (normales 0,1) de dimensiones nxm y mxn
- Haga el producto matricial de ambas para obtener una matriz nxn. 

In [14]:
def mxn(a,b):

    x = np.random.rand(a, b)
    y = np.random.rand(b, a)
    
    return np.dot(x,y)

In [15]:
mxn(5,10)

array([[1.81513082, 1.85766995, 1.45510752, 2.03619213, 1.56466396],
       [2.77420835, 2.68796942, 2.12581695, 2.36617271, 1.8047049 ],
       [1.83065919, 2.0085336 , 1.82655089, 2.11626344, 2.21727789],
       [2.51731932, 2.51943186, 1.58716631, 1.8833131 , 1.39616494],
       [2.96169186, 3.03397983, 2.36471108, 2.61491079, 2.13350341]])

**2.1.9.** Calule el capital final de invertir 500€ mensuales durante 10 años, a un interés anual del 10%

In [29]:
import numpy_financial as npf

In [30]:
npf.fv(rate = 0.1/12, nper = 10*12, pmt = 500, pv = 0)

-102422.48945173463

### 2.2. Introducción a Pandas I.

**2.2.1.**  Crea un dataframe a partir del diccionario, usando la lista como índice.

In [ ]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
df = pd.DataFrame(data, index=labels)
df

**2.2.2.**  Muestra una descripción de los datos.

In [ ]:
df.describe()

**2.2.3.**  Muestra las 2 primeras filas.

In [ ]:
df.loc[['a','b']]

In [ ]:
df.iloc[0:2, :]

**2.2.4.**  Muestra la tercera columna.

In [ ]:
df.iloc[:, 3]

**2.2.5.**  Selecciona las columnas animal y age.

In [ ]:
df.loc[:, ['animal', 'age']]

**2.2.6.**  Elimina la columna visits sin generar un nuevo DF.

In [ ]:
del df['animal']

In [ ]:
df.drop('age', axis=1)

In [ ]:
df.drop(['visits'], axis=1, inplace=True)

In [ ]:
df

**2.2.8.**  Elimina la fila c.

In [ ]:
df = df.drop('c', axis=0)

**2.2.9.**  Crea una columna nueva con los valores de 0 a 8

In [ ]:
df['new'] = range(9)
df

**2.2.10.** Crea a partir de los siguientes datos un Data Frame

- planets: "Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"
- type: "Terrestrial planet", "Terrestrial planet", "Terrestrial planet", "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant"
- diameter 0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883
- rotation 58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67
- rings FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE

Resuelve los siguientes apartados:

- Selecciona la información de los tres primeros planetas.
- Selecciona la información de los últimos tres planetas.
- Selecciona la columna diameter de los últimos seis planetas. 
- Selecciona sólo los planetas que tienen anillos.
- Selecciona los planetas que tienen un diámetro inferior al de la tierra .
- Ordena el Data Frame según el diámetro de los planetas, ascendentemente.

In [ ]:
a = pd.Series(["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"] , name = "planetas")
b = pd.Series(["Terrestrial planet", "Terrestrial planet", "Terrestrial planet", "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant"], name = "tipo")
c = pd.Series([0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883], name = "diametro")
d = pd.Series([58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67], name = "rotacion")
e = pd.Series([False, False, False, False, True, True, True, True], name = "anillos")

frame = pd.DataFrame([b, c, d, e]).T
frame.index = a

frame

In [ ]:
# Otra manera de hacerlo

a = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]
b = ["Terrestrial planet", "Terrestrial planet", "Terrestrial planet", "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant"]
c = [0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883]
d = [58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67]
e = [False, False, False, False, True, True, True, True]

frame = pd.DataFrame([a, b, c, d, e]).T
frame

In [ ]:
# Selecciona la información de los tres primeros planetas.

frame.loc['Mercury':'Earth',:]

In [ ]:
# Selecciona la información de los últimos tres planetas.

frame.iloc[-4:-1,:]

In [ ]:
# Selecciona la columna diameter de los últimos seis planetas. 

frame.loc['Earth':'Neptune','diametro']

In [ ]:
# Selecciona sólo los planetas que tienen anillos.

ind_bool = frame.anillos == True

frame[ind_bool] # Recuerda que el índice principal son las filas

In [ ]:
# Selecciona los planetas que tienen un diámetro inferior al de la tierra.

ind_bool = frame.diametro < frame.loc['Earth', 'diametro']

frame[ind_bool]

In [ ]:
# Ordena el Data Frame según el diámetro de los planetas, ascendentemente.

frame.sort_values('diametro')

___
### 2.3. Introducción a Pandas II.

**2.3.1.** Usando los siguientes daframe:

In [ ]:
df_a = pd.DataFrame(np.random.randint(1, 10, 10),
                    index=np.arange(1, 11))
df_a

In [ ]:
df_b = pd.DataFrame(np.random.randint(1, 10, 10),
                    index=np.arange(0, 10))
df_b

Calcula la resta de ambos y explica la diferencia entre usar un relleno = 0 o no.

In [ ]:
df_a - df_b

In [ ]:
df_a.sub(df_b, fill_value=0)

___
### 2.4. Introducción a Pandas III.

Utilizando el siguiente dataframe:

In [ ]:
df = pd.DataFrame({"price": [5,2,3,1,4,5,6,7,8,3,4,8,9],
                   "hours"    :[1,9,6,5,3,9,2,9,1,7,4,2,2],
                   "happiness"   :[2,1,3,2,3,1,2,3,1,2,2,1,3],
                   "caffienated" :[0,0,1,1,0,0,0,0,1,1,0,1,0]})

**2.4.1.** 

- Calcula la media del precio.
- Calcula la mutltiplicación de price x hours.

In [ ]:
df.mean()

In [ ]:
df.price.mean()

In [ ]:
df.price*df.hours

**2.4.2.** En bikes.csv encontrarás información agregada por horas de un sistema de alquiler de bicicletas (parecido al servicio BiciMad). 

Las variables del  dataset   son las siguientes:  

- date:  fecha (en formato yyyy­mm­dd).  
- season:  estación del año. Los valores son:  
    o	1 (winter)  
    o	2 (spring)  
    o	3 (summer)  
    o	4 (fall)  
- hour:  la hora del día (0 a 23).  
- is.holiday:  1 si es día festivo, 0 en caso contrario.  
- weekday:  día de la semana. Los valores son:  
o	0 (Sunday)  
o	1 (Monday)  
o	2 (Tuesday)  
o	3 (Wednesday)  
o	4 (Thursday)  
o	5 (Friday)  
o	6 (Saturday)  
- is.workingday:  si el día no es ni fin de semana ni vacaciones 1, en caso contrario 0.  
- weathersit:  variable categórica con los siguientes valores:  
o	1: Clear, Few clouds, Partly cloudy, cloudy  
o	2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist  
o	3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds  
o	4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog  
- temp:  temperatura en grados Celsius.  
- atemp:  sensación térmica en grados Celsius.  
- hum:  humedad.  
- windspeed:  velocidad del viento.  
- casual:  número de alquileres de usuarios no registrados en el servicio.  
- registered:  número de alquileres de usuarios registrados en el servicio. 

Carga el csv y asegúrate que es un dataframe

In [ ]:
bicis_df = pd.read_csv('bikes.csv') 

In [ ]:
type(bicis_df)

In [ ]:
bicis_df.head(5)

**2.4.3.** Calcula el número medio de usuarios registrados por día de la semana

In [ ]:
usu_medio = list()

for dia in range(7):
    
    respuesta = bicis_df.loc[bicis_df.weekday == dia,:].registered.mean()
    usu_medio.append(f'Día {dia} número medio de usuarios {int(respuesta)}')

usu_medio

**2.4.4.** Ordena de menor a mayor las temperaturas máximas de cada estación

In [ ]:
temperaturas = list()

for est in range(1, 5):
    
    solucion = bicis_df.loc[bicis_df.season == est, 'temp'].max()
    temperaturas.append(solucion)
    
temperaturas.sort()
temperaturas

**2.4.5.** Calcula el número total de usuarios (registered + casual) en días festivos y no festivos.

In [ ]:
bicis_df.columns = ['date', 'season', 'hour', 'is_holiday', 'weekday', 'is_workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered']
bicis_df.head(5)

In [ ]:
tot_usu_fest = bicis_df.loc[bicis_df.is_holiday == 1,['casual', 'registered']].sum()
tot_usu_no_fest = bicis_df.loc[bicis_df.is_holiday == 0,['casual', 'registered']].sum()

print(tot_usu_fest)
print(tot_usu_no_fest)

**2.4.6.** Calcula el día que se produjeron el mayor número de alquileres casuales.

In [ ]:
bicis_df.loc[bicis_df.casual == bicis_df.casual.max(),'date']

**2.4.7.** Calcula el ratio de alquileres registrados/casuales por hora en verano.

In [ ]:
ratio_hora = list()

for hora in range(24):
    casual, registered = bicis_df.loc[(bicis_df.season == 3) & (bicis_df.hour == hora), ['casual', 'registered']].sum()
    ratio_hora.append(f' Hora {hora}, ratio = {registered / casual}')

ratio_hora

**2.4.8.** Para todos los lunes festivos calcular el número total de alquileres registrados, temperatura media, humedad máxima y velocidad del viento mínima.

In [ ]:
lunes_festivos = bicis_df.loc[(bicis_df.weekday == 1) & (bicis_df.is_holiday == 1),:]

lunes_festivos.head(5)

In [ ]:
num_total_alq = lunes_festivos.registered.sum()

tem_media = lunes_festivos.temp.mean()

hum_max = lunes_festivos.hum.max()

vel_viento_min = lunes_festivos.windspeed.min()

f'El número total de alquileres registrados fue {num_total_alq}, la temperatura media {round(tem_media,2)}, la humedad máxima {hum_max} y la velocidad del viento mínima {vel_viento_min}'

### 2.5. Visualización de datos.

**2.5.1.** Usando:

In [ ]:
x = np.arange(0,100)
y = x*2
z = x**2

Crea el gráfico de x contra y.

In [ ]:
plt.plot(x, y)

**2.5.2.** Crea un gráfico de dos columnas y una fila con (x, y) y (x, z), añade una leyende a cada gráfico y utiliza un estilo distinto de línea y marker para cada uno.

In [ ]:
fig, (ax_a, ax_b) = plt.subplots(1, 2)
ax_a.plot(x, y)
ax_b.plot(x, z)

**2.5.3.** Aumenta el gráfico anterior de tamaño.

In [ ]:
fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=(10,7))
ax_a.plot(x, y)
ax_b.plot(x, z)

**2.5.4.** Guardalo en un fichero.

In [ ]:
fig.savefig('fig.png')

___
### 2.6. Adquisición y guardado de datos.

**2.6.1.** Lee los datos del fichero train.txt.

In [ ]:
data = pd.read_csv('train.csv')

**2.6.2.** Cambia algunos de los datos y escribe el fichero train_mod.csv.

In [ ]:
data.iloc[2:20, 5:10] = 0

In [ ]:
data.to_csv('train_mod.csv')